"""Developer-only deterministic native hook build. Owner uses xt30_battery.py."""
import argparse
import hashlib
from pathlib import Path
import subprocess
from elftools.elf.elffile import ELFFile


def build(toolchain, check=False):
    root = Path(__file__).resolve().parent
    folder = root / 'build/warning-hook'
    folder.mkdir(parents=True, exist_ok=True)
    output = folder / 'warning_hook.elf'
    subprocess.run([str(toolchain / 'clang.exe'), '--target=armv7a-linux-androideabi21',
        '-mthumb', '-march=armv7-a', '-mfloat-abi=soft', '-Oz', '-ffreestanding',
        '-fno-builtin', '-fno-stack-protector', '-fomit-frame-pointer',
        '-fno-unwind-tables', '-fno-asynchronous-unwind-tables', '-nostdlib', '-static',
        '-Wl,-T,' + str(root / 'src/native/warning_hook.ld'), '-Wl,--build-id=none',
        '-Wl,-no-pie', str(root / 'src/native/warning_hook.c'), '-o', str(output)], check=True)
    with output.open('rb') as stream:
        elf = ELFFile(stream)
        section = elf.get_section_by_name('.text')
        data = section.data()
        symbols = {s.name: s['st_value'] for s in elf.get_section_by_name('.symtab').iter_symbols()}
        if any(s['sh_type'] in ('SHT_REL', 'SHT_RELA') and s['sh_size'] for s in elf.iter_sections()):
            raise RuntimeError('hook must not have relocations')
        if symbols['warning_config'] != section['sh_addr'] or data[:16] != bytes(16):
            raise RuntimeError('unexpected config placement')
        entry = symbols['warning_hook'] - section['sh_addr']
    if len(data) > 0x576E8 - 0x574A4 or entry != 17:
        raise RuntimeError('hook exceeds verified padding or entry changed')
    source = ('# Generated by build_warning_hook.py; own freestanding code, no vendor bytes.\n'
              'ENTRY = %d\nSHA256 = %r\nBLOB = bytes.fromhex(\n' % (entry, hashlib.sha256(data).hexdigest()))
    hx = data.hex()
    source += ''.join('    %r\n' % hx[i:i+96] for i in range(0, len(hx), 96)) + ')\n'
    target = root / 'src/warning_hook_blob.py'
    if check:
        if target.read_text(encoding='utf-8') != source:
            raise RuntimeError('native hook bundle needs rebuilding')
    else:
        target.write_text(source, encoding='utf-8', newline='\n')
    print('Native hook verified: %d bytes, entry %d, SHA256 %s' %
          (len(data), entry, hashlib.sha256(data).hexdigest()))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--toolchain', required=True, type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    build(args.toolchain, args.check)
