#!/usr/bin/env python3
"""Build the single pasteable Lab script from its readable worker and launcher."""
import argparse
import base64
import hashlib
import importlib.util
import json
from pathlib import Path


def validate_launcher(source):
    # The DJI project parser rewrites escapes before Python sees the source.
    decoded = source.replace('\\n', '\n').replace('\\"', '"')
    if decoded != source:
        raise RuntimeError('launcher contains escape sequences rewritten by the DJI project parser')
    compile(source, 'xt30_battery.py', 'exec')


def build(check=False):
    root = Path(__file__).resolve().parent
    spec = importlib.util.spec_from_file_location('battery_bundle', root / 'src' / 'build_bundle.py')
    bundle = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(bundle)
    payload = json.dumps(bundle.payload_files(), sort_keys=True, separators=(',', ':')).encode('utf-8')
    template = (root / 'src' / 'lab_launcher.template.py').read_text(encoding='utf-8')
    for marker in ('__BUNDLE_B64__', '__BUNDLE_SHA256__'):
        if template.count(marker) != 1:
            raise RuntimeError('expected one template marker: ' + marker)
    output = template.replace('__BUNDLE_B64__', base64.b64encode(payload).decode('ascii'))
    output = output.replace('__BUNDLE_SHA256__', hashlib.sha256(payload).hexdigest())
    output = '# Generated by build_lab_script.py; edit the readable sources and rebuild.\n' + output
    validate_launcher(output)
    path = root / 'scripts' / 'xt30_battery.py'
    if check:
        if not path.is_file() or path.read_text(encoding='utf-8') != output:
            raise RuntimeError('generated Lab script needs rebuilding')
        print('Generated Lab script matches its sources.')
    else:
        path.parent.mkdir(exist_ok=True)
        path.write_text(output, encoding='utf-8', newline='\n')
        print(path)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    build(parser.parse_args().check)
